articles/urls.py
# -*- coding: utf-8 -*-
# @author ZhengZhong,Jiang
# @time 2017/7/28 14:43
from django.conf.urls import url
from views import ArticleListView, ArticleDetailView, ArticleCreateView

urlpatterns = [
    url(r'^list/$', ArticleListView.as_view(), name='article_list'),
    url(r'^detail/(?P<article_id>\d+)/$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^create/$', ArticleCreateView.as_view(), name='article_create')
]

blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.views.static import serve

from blog.settings import MEDIA_ROOT

from articles.views import ArticleListView
from users.views import UserLoginView, UserRegisterView, UserLogoutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', UserLoginView.as_view(), name='login'),
    url(r'^logout/', UserLogoutView.as_view(), name='logout'),
    url(r'^register/', UserRegisterView.as_view(), name='register'),
    url(r'^$', ArticleListView.as_view(), name='index'),
    url(r'^article/', include('articles.urls', namespace='article')),

    url(r'^media/(?P<path>.*)/$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^captcha/', include('captcha.urls')),

]


templates/base.html
<!DOCTYPE HTML>
<html>
    {% load staticfiles %}
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Story &mdash; Free Website Template, Free HTML5 Template by freehtml5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="freehtml5.co" />

	

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

{#    <script src="{% static 'js/ckeditor.js' %}"></script>#}
{#    <script src="https://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>#}
        {% block head_js %}{% endblock %}

	</head>
	<body>

		
	<div class="fh5co-loader"></div>

	<div id="page">
		<div id="fh5co-aside" style="background-image: url({% static 'images/image_1.jpg' %})">
			<div class="overlay"></div>
			<nav role="navigation">
				<ul>
					<li><a href="{% url 'index' %}"><i class="icon-home"></i></a></li>
                    <li><a href="{% url 'article:article_create' %}"><i class="icon-clipboard"></i></a></li>
                    <li><a href="{% url 'logout' %}"><i class="icon-log-out"></i></a></li>
{#                    <li><a href="{% url 'user:article_create' %}"><i class="icon-clipboard"></i></a></li>#}
				</ul>
			</nav>
			<div class="featured">
				<span>Bio</span>
				<h2>I'm {{ username }}</h2>
			</div>
		</div>
		<div id="fh5co-main-content">
			<div class="fh5co-post">
                {% block custom %}{% endblock %}
				<footer>
					<div>
					&copy; 2016 Free HTML5. All Rights Reserved. More Templates
					</div>
				</footer>
			</div>
		</div>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

    {% block custom_js %}{% endblock %}

	</body>
</html>

templates/base2.html
<!DOCTYPE HTML>
<html>
    {% load staticfiles %}
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Story &mdash; Free Website Template, Free HTML5 Template by freehtml5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="freehtml5.co" />

	

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

{#    <script src="{% static 'js/ckeditor.js' %}"></script>#}
{#    <script src="https://cdn.ckeditor.com/4.7.1/standard/ckeditor.js"></script>#}
        {% block head_js %}{% endblock %}

	</head>
	<body>

{#    <section class="headerwrap headerwrap2">#}
{#    <header>#}
{#		<div  class="header2 header">#}
{# 			<div class="top">#}
{#				<div class="wp">#}
{#					<div class="fl"><p>服务电话：<b>400-8886888</b></p></div>#}
{#					<!--登录后跳转-->#}
{#                        <div class="personal">#}
{#                            <dl class="user fr">#}
{#                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>#}
{#                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>#}
{#                            </dl>#}
{#                            <div class="userdetail">#}
{#                            	<dl>#}
{#	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>#}
{#	                                <dd>#}
{#	                                    <h2>{{ request.user.nick_name }}</h2>#}
{#	                                    <p>{{ request.user.username }}</p>#}
{#	                                </dd>#}
{#                                </dl>#}
{#                                <div class="btn">#}
{#                                    <a class="personcenter fl" href="{% url 'articles:add' %}">新建博客</a>#}
{#	                                <a class="personcenter fl" href="{% url 'user:user_info' %}">个人中心</a>#}
{#	                                <a class="fr" href="{% url 'logout' %}">退出</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <a href="{% url 'user:user_msg' %}">#}
{#                            <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>#}
{#                        </a>#}
{#				</div>#}
{#			</div>#}
{##}
{#    <div class="middle">#}
{#        <div class="wp">#}
{#            <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>#}
{#            <h1>我的空间</h1>#}
{#        </div>#}
{#    </div>#}
{#			</div>#}
{#    </header>#}
{#</section>#}
		
	<div class="fh5co-loader"></div>

	<div id="page">
		<div id="fh5co-aside" style="background-image: url({% static 'images/image_1.jpg' %})">
			<div class="overlay"></div>
			<nav role="navigation">
				<ul>
					<li><a href="{% url 'index' %}"><i class="icon-home"></i></a></li>
                    <li><a href="{% url 'article:article_create' %}"><i class="icon-clipboard"></i></a></li>
{#                    <li><a href="{% url 'user:article_create' %}"><i class="icon-clipboard"></i></a></li>#}
				</ul>
			</nav>
			<div class="featured">
				<span>Bio</span>
				<h2>I'm John Doe</h2>
			</div>
		</div>
		<div id="fh5co-main-content">
			<div class="fh5co-post">
                {% block custom %}{% endblock %}
				<footer>
					<div>
					&copy; 2016 Free HTML5. All Rights Reserved. More Templates
					</div>
				</footer>
			</div>
		</div>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

    {% block custom_js %}{% endblock %}

	</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_js %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}
{% block custom %}
    <div class="fh5co-entry padding">
        <form action="{% url 'article:article_create' %}">
            <div>
                <label>文章标题</label>
                <input type="text" name="title" value="" id="js-pl-1">
            </div>
            <div>
                <label>文章描述</label>
                <input type="text" name="title" value="" id="js-pl-2">
            </div>
            <div>
                <label>文章分类</label>
                <select id="js-pl-3">
                    {% for item in article_category %}
                        <option value="{{ item.id }}">{{ item.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label id="js-pl-4">文章标签</label>
                {% for item in article_tag %}
                <input type="checkbox" name="tag" value="{{ item.id }}">{{ item.name }}
                {% endfor %}
            </div>
            <textarea name="editor1" id="editor1"></textarea>
            <script>
                CKEDITOR.replace( 'editor1' );
            </script>
        <div>
            <button type="button" id="js-pl-submit">保存</button>
        </div>
        </form>
    </div>
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
        //添加文章
        $('#js-pl-submit').on('click', function(){
            var article_tag = [];
            var article_title = $("#js-pl-1").val();
            var article_desc = $("#js-pl-2").val();
            var article_category = $("#js-pl-3").val();
{#            var article_tag = $("input[name='tag']:checked").serialize();#}
            $('input:checkbox:checked').each(function() {
                article_tag.push($(this).val());
            });

            var article_content =  CKEDITOR.instances.editor1.getData();

            console.log(article_category);
            console.log(article_tag);
            console.log(article_content);
{#            if(article_content == ""){#}
{#                alert("文章内容不能为空");#}
{#                return#}
{#            }#}
            $.ajax({
                cache: false,
                traditional: true,
                type: "POST",
                url:"{% url 'article:article_create' %}",
                data:{'title':article_title, 'desc':article_desc,
                    'category': article_category, 'tag': article_tag,
                    'content': article_content},
                async: true,
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    if(data.status == 'fail'){
{#                        if(data.msg == '用户未登录'){#}
{#                            window.location.href="/login/";#}
{#                        }else{#}
                            alert(data.msg)
                        }
{##}
                    else if(data.status == 'success'){
{#                        window.location.reload();//刷新当前页面.#}
{#                        alert(data.msg);#}
                        window.location.href = "/article/detail/"+data.msg;
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/detail.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Story &mdash; Free Website Template, Free HTML5 Template by freehtml5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="freehtml5.co" />

	

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body class="single">
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
		<div id="fh5co-aside" style="background-image: url({% static 'images/image_1.jpg' %})" data-stellar-background-ratio="0.5">
			<div class="overlay"></div>
			<nav role="navigation">
				<ul>
					<li><a href="{% url 'index' %}"><i class="icon-home"></i></a></li>
				</ul>
			</nav>
			<div class="page-title">
				<img src="{% static 'images/person_1.jpg' %}" alt="Free HTML5 by FreeHTMl5.co">
				<span>{{ article.date_published }}</span>
				<h2>{{ article.title }}</h2>
			</div>
		</div>
		<div id="fh5co-main-content">
			<div class="fh5co-post"> 
				<div class="fh5co-entry padding">
					<div>
                        {% autoescape off %}
                        <p>{{ article.content }}</p>
					    {% endautoescape %}
                    </div>
				</div>
			</div>
		</div>
	</div>

	<div class="fh5co-navigation">
		<div class="fh5co-cover prev fh5co-cover-sm" style="background-image: url({% static 'images/project-4.jpg' %})">
			<div class="overlay"></div>

			<a class="copy" href="{% url 'article:article_detail' previous_article.id %}">
				<div class="display-t">
					<div class="display-tc">
						<div>
							<span>Previous Post</span>
							<h2>{{ previous_article.title }}</h2>
						</div>
					</div>
				</div>
			</a>

		</div>
		<div class="fh5co-cover next fh5co-cover-sm" style="background-image: url({% static 'images/project-5.jpg' %})">
			<div class="overlay"></div>
			<a class="copy" href="{% url 'article:article_detail' next_article.id %}">
				<div class="display-t">
					<div class="display-tc">
						<div>
							<span>Next Post</span>
							<h2>{{ next_article.title }}</h2>
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<footer>
		<div>
        &copy; 2016 Free HTML5. All Rights Reserved. Designed by <a href="" target="_blank">FreeHTML5</a>
        </div>
    </footer>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/detail2.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom %}
    <div class="fh5co-entry padding">
        <img src="{% static 'images/project-1.jpg' %}" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">
        <div>
            <span class="fh5co-post-date">October 12, 2016</span>
            <h2><a href="{% url 'article:article_detail' %}">How to be an effective web developer</a></h2>
            <p>How two simple exercises changed my life</p>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom %}
{#    <div class="fh5co-entry padding">#}
{#        <img src="{% static 'images/project-1.jpg' %}" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">#}
{#        <div>#}
{#            <span class="fh5co-post-date">October 12, 2016</span>#}
{#            <h2><a href="{% url 'article:article_detail' article_id %}">How to be an effective web developer</a></h2>#}
{#            <p>How two simple exercises changed my life</p>#}
{#        </div>#}
{#    </div>#}
    {% for article in all_article.object_list %}
        <div class="fh5co-entry padding">
        <img src="{{ MEDIA_URL }}{{ article.user.avatar }}" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">
            <div>
                <span class="fh5co-post-date">{{ article.date_published }}</span>
                <h2><a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a></h2>
                <p>{{ article.desc }}</p>
            </div>
        </div>
    {% endfor %}
    <div class="pageturn">
        <ul class="pagelist">
            {% if all_article.has_previous %}
                <li class="long"><a href="?{{ all_article.previous_page_number.querystring }}">上一页</a></li>
            {% endif %}
            {% for page in all_article.pages %}
                {% if page %}
                    {% ifequal page all_article.number %}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="none"><a href="">...</a> </li>
                {% endif %}
            {% endfor %}
            {% if all_article.has_next %}
                <li class="long"><a href="?{{ all_article.next_page_number.querystring }}">下一页</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="application/javascript">
        {% for article in all_article.object_list %}
            console.log({{ article.user.avatar }})
        {% endfor %}
    </script>
{% endblock %}

templates/login.html
{% extends 'user_base.html' %}
{% block custom_user %}
    <div class="content1">
		<h2>Sign In Form</h2>
		<form method="post">
			<input type="text" name="username" value="USERNAME" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'USERNAME';}">
			<input type="password" name="password" value="PASSWORD" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">
			<div class="button-row">
				<input type="submit" class="sign-in" value="Sign In">
				<input type="reset" class="reset" value="Reset">
				<div class="clear"></div>
			</div>
            {% csrf_token %}
		</form>
	</div>
{% endblock %}

templates/register.html
{% extends 'user_base.html' %}
{% block custom_user %}
	<div class="content2">
		<h2>Sign Up Form</h2>
		<form method="post">
			<input type="text" name="username" value="USERNAME" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'NAME AND SURNAME';}">
			<input type="tel" name="phone" value="PHONE" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PHONE';}">
            <input type="password" name="psw1" value="PASSWORD" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">
			<input type="password" name="psw2" value="PASSWORD" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">
            <div class="{% if register_form.errors.captcha %}errorput{% endif %}">
                {{ register_form.captcha }}
            </div>
{#            <input type="text" name="captcha" value="CAPTCHA" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'CAPTCHA';}">#}
			<input type="submit" class="register" value="Register">
            {% csrf_token %}
		</form>
	</div>
{% endblock %}

templates/user_base.html
<!doctype html>
<html>
{% load staticfiles %}
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- font files  -->
{#<link href='http://fonts.useso.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>#}
{#<link href='http://fonts.useso.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>#}
<!-- /font files  -->
<!-- css files -->
<link href="{% static 'css/style_user.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css files -->
</head>
<body>
<h1>User Login</h1>
<div class="log">
{#	<div class="content1">#}
{#		<h2>Sign In Form</h2>#}
{#		<form>#}
{#			<input type="text" name="userid" value="USERNAME" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'USERNAME';}">#}
{#			<input type="password" name="psw" value="PASSWORD" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">#}
{#			<div class="button-row">#}
{#				<input type="submit" class="sign-in" value="Sign In">#}
{#				<input type="reset" class="reset" value="Reset">#}
{#				<div class="clear"></div>#}
{#			</div>#}
{#		</form>#}
{#	</div>#}
    {% block custom_user %}
    {% endblock %}
	<div class="clear"></div>
</div>
<div class="footer">
	<p>Copyright &copy; 2016.Company name All rights reserved.</p>
</div>

</body>
</html>